theme: jekyll-theme-minimal
title: W3C Credentials Community Group
logo: assets/img/logo.png
description: The W3C Credentials Community Group Landing Page.
show_downloads: true
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
google_analytics:
